# ============ 基本信息（改这里）============
title: Weiya Wang
description: PhD student in Electronic Engineer. I work on First principle calculation, microelectronic device, Condense matter physics and neuromorphic computing(neuromorphic dynamics). Previously, my research focused on multimodal information processing, pretrained model and deep learning.I also have some interest on the interact for AI and science.
lang: en
url: "https://scholar.google.com/citations?user=-GcNn88AAAAJ&hl=zh-CN"   # 改成你的 GitHub Pages 地址
baseurl: ""

author:
  name: Weiya Wang
  position: PhD Student, Electronic Engineer
  affiliation: TU Berlin
  affiliation_url: https://www.tu.berlin
  avatar: /assets/img/avatar.svg     # 换成你的照片，比如 /assets/img/me.jpg
  email: wwy20@tsinghua.org.cn

# 论文作者列表里需要加粗的名字（必须和 publications.yml 里的写法完全一致）
scholar_name: Weiya Wang

# 主页头像下方的链接，不需要的删掉即可
social:
  - name: Email
    url: wwy20@tsinghua.org.cn
  - name: Google Scholar
    url: https://scholar.google.com/citations?user=-GcNn88AAAAJ&hl=zh-CN
  #- name: GitHub
    #url: https://github.com/yourname
  #- name: CV
    #url: /assets/cv.pdf

# 顶部导航
nav:
  - name: Home
    url: /
  - name: Publications
    url: /publications/
  - name: Blog
    url: /blog/

news_limit: 6   # 首页显示几条新闻，其余折叠

# ============ 以下一般不用改 ============
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
feed:
  path: /blog/feed.xml
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
